# Generated by Django 4.0.6 on 2022-07-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalAppD', '0003_remove_resource_link_remove_resource_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
    ]
